[package]
name = "transform"
version = "0.1.0"
edition = "2024"

[dependencies]
spargebra = "0.4.0-beta.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
spareval = "0.2.0-beta.3"
clap = { version = "4.0", features = ["derive"] }
